services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure:5 
    ports:
      - "5433:5432"
    networks: 
      - pg_network
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

networks:
  pg_network: