name: lint

on: 
    pull_request:

jobs:   
  golangci-lint:
    env:
        GOFLAGS: "-buildvcs=false"
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./       